In [1]:
import pandas as pd

In [86]:
filename = "restart.xlsx"
df = pd.read_excel(filename)

In [87]:
df2 = df.loc[:83, ["Q1 Prediction", "Q1 Projected Score", "Q2 Prediction", "Q2 Projected Score", "Q3 Prediction", "Q3 Projected Score", "Final Total"]]
df2

,Q1 Prediction,Q1 Projected Score,Q2 Prediction,Q2 Projected Score,Q3 Prediction,Q3 Projected Score,Final Total
0,227.577661,220.0,218.198553,215.5,208.300,208.5,204
1,241.477276,233.5,238.674110,233.5,246.890,246.5,246
2,240.108958,235.5,243.797056,241.5,247.630,247.5,275
3,247.118431,230.5,236.267580,235.5,228.200,225.5,237
4,227.709058,232.5,234.846761,231.5,230.000,230.5,231
5,245.576540,240.5,242.449582,239.5,245.600,237.5,249
6,263.236682,256.5,278.382283,274.5,286.200,285.5,302
7,219.313871,209.5,222.908237,213.5,227.300,218.5,230
8,208.011294,208.5,217.435473,217.5,200.380,206.5,204
9,237.892512,232.5,238.498554,232.5,223.460,226.5,229
10,228.402446,230.5,224.693532,226.5,222.550,223.5,248
11,208.604600,209.5,194.552994,192.5,196.000,193.5,199
12,218.723162,215.5,223.607922,220.5,226.160,226.5,228
13,232.884456,231.5,228.696752,229.5,236.690,238.5,252
14,229.693866,235.5,228.040234,231.5,217.860,223.5,214
15,232.106641,229.5,241.139866,242.5,244.120,245.5,248
16,237.493163,245.5,232.998521,237.5,236.920,241.5,236
17,231.746909,232.5,248.457952,246.5,245.860,249.5,232
18,204.552829,211.5,201.783792,208.5,213.600,205.5,210
19,208.476514,208.5,209.992291,206.5,213.700,207.5,234
20,211.512077,209.5,216.796078,210.5,211.200,212.5,211
21,222.752887,224.5,225.190178,226.5,210.300,211.5,208
22,237.336404,237.5,238.578692,239.5,242.300,236.5,262
23,212.698804,211.5,224.004678,220.5,216.100,212.5,224
24,246.332338,245.5,251.860979,251.5,238.430,241.5,235
25,235.204840,243.5,229.012731,232.5,212.700,215.5,224
26,228.360814,232.5,228.800513,231.5,221.300,223.5,229
27,228.137831,226.5,224.787841,226.5,229.100,229.5,218
28,230.542177,240.5,234.920000,236.5,224.090,230.5,212
29,226.970000,221.5,231.120000,230.5,233.790,236.5,239
...,...,...,...,...,...,...,...
54,221.700000,226.5,237.800000,239.5,240.290,240.5,245
55,232.810000,232.5,231.940000,236.5,219.440,232.0,241
56,241.390000,235.5,250.800000,253.5,249.310,254.5,249
57,229.180000,225.5,241.090000,238.5,234.310,233.5,229
58,238.710000,234.5,236.860000,233.5,244.000,242.5,236
59,236.840000,237.5,232.430000,232.5,217.320,219.5,220
60,203.780000,210.5,205.266000,206.5,209.720,212.5,206
61,221.640000,222.5,233.210000,232.5,231.670,229.5,245
62,221.240000,224.5,212.270000,215.5,211.170,212.5,204
63,233.140000,234.5,232.490000,232.5,232.990,234.5,228
64,217.560000,222.5,232.780000,235.5,241.577,241.5,247
65,245.180000,247.5,240.230000,246.5,251.560,254.5,265
66,209.510000,212.5,205.287000,210.5,211.200,213.5,229
67,229.060000,233.5,237.900000,239.5,235.320,235.5,218
68,220.430000,216.5,239.230000,224.5,240.360,240.5,239
69,233.690000,235.5,214.210000,217.5,212.240,215.5,212
70,221.500000,222.5,226.250000,227.5,233.270,234.5,246
71,238.564000,236.5,238.450000,236.5,236.470,237.5,231
72,218.890000,222.5,219.770000,222.5,238.403,238.5,235
73,219.885000,214.5,222.020000,219.5,212.149,207.5,186
74,236.310000,236.5,223.768000,232.5,219.800,220.5,230
75,234.940000,239.5,248.460000,250.5,238.720,241.5,230
76,235.495000,235.5,251.120000,250.5,242.524,247.5,260
77,214.292000,215.5,224.546000,224.5,222.240,224.5,225
78,238.220000,236.5,232.894000,232.5,245.633,243.5,258
79,235.040000,243.5,255.010000,257.5,259.280,261.5,267
80,237.510000,237.5,231.950000,231.5,234.980,235.5,230
81,205.160000,206.5,211.496000,211.5,207.640,206.5,199
82,209.780000,212.5,195.005000,196.5,187.014,190.5,210
83,218.960000,229.5,217.528000,219.5,215.130,219.5,226

In [88]:
df2.iloc[12]["Final Total"]

228.0

In [117]:
#returns suggested base amount for bet
#over/unders are generally in slight minus odds, for the purpose of this excercise we will assume a line of -112
#This means a $112 dollar bet pays out $100
#For the example above this function should return 112, NOT 100
#If using this function for purposes other than this excercise, all values can be scaled by a constant value to fit
#your personal financial constraints
#returns 0 if prediction and projection are within threshold
def wager(thresh, base, rate, pred, proj):
    value = 0
    thresh2 = thresh
    if pred<=proj:
        thresh2 = -1*thresh
        
    if abs(pred-proj)<=thresh:
        return value
    else:
        value = base + rate*abs(pred-proj-thresh2)
        return value

In [118]:
wager(2, 1, 1, 200, 199)

0

In [119]:
print(wager(2, 1, 1, 200, 201))
print(wager(2,1,1, 200, 203))
print(wager(2, 1, 1, 200, 199))
print(wager(2,1,1, 200, 197))

0
2
0
2

In [120]:
#iterates through seeding games and simulates wagering strategy

def test_strat(init, thresh, base, rate):
    print("Initial Balance: $",init)
    balance = init
    staked = 0
    vig = 0.8928571429
    wagered = 0
    wins = 0
    for i in range(84):
        for j in range(1,4):
            final = df2.iloc[i]["Final Total"]
            model = df2.iloc[i]["Q"+str(j)+" Prediction"]
            line = df2.iloc[i]["Q"+str(j)+" Projected Score"]
            wag = wager(thresh, base, rate, model, line)
            wagered = wagered + (wag!=0)
            if final == line:
                balance = balance +0
            elif (model<line) == (final<line):
                balance = balance + vig*wag
                wins = wins + (wag!=0)
            else:
                balance = balance - wag
            staked = staked + wag
    roi = 1.0*(balance-init)/staked
    avg_wag = staked/wagered
    win_rate = wins/wagered
    print("Final Balance: $",balance)
    print("Total Staked: $",staked)
    print("ROI: ", roi)
    print("Average wager: $", avg_wag)
    print("Win Rate: ", win_rate)

In [121]:
test_strat(500, 2, 5, 5)

Initial Balance: $ 500
Final Balance: $ 1161.8143808195114
Total Staked: $ 2521.4046174359305
ROI:  0.2624784519878148
Average wager: $ 18.13960156428727
Win Rate:  0.60431654676259

In [122]:
test_strat(500, 2, 1, 10)

Initial Balance: $ 500
Final Balance: $ 1643.6287616066215
Total Staked: $ 3791.80923487186
ROI:  0.30160503621571805
Average wager: $ 27.279203128574533
Win Rate:  0.60431654676259

In [123]:
test_strat(500, 5, 20, 0)

Initial Balance: $ 500
Final Balance: $ 827.1428571719991
Total Staked: $ 960.0
ROI:  0.34077380955416575
Average wager: $ 20.0
Win Rate:  0.7083333333333334

In [124]:
test_strat(500, 2, 5, 5)

Initial Balance: $ 500
Final Balance: $ 1161.8143808195114
Total Staked: $ 2521.4046174359305
ROI:  0.2624784519878148
Average wager: $ 18.13960156428727
Win Rate:  0.60431654676259

In [125]:
test_strat(500, 5, 10, 4)

Initial Balance: $ 500
Final Balance: $ 872.2152259219102
Total Staked: $ 948.5171429820837
ROI:  0.39241802710248
Average wager: $ 19.760773812126743
Win Rate:  0.7083333333333334

In [126]:
test_strat(500, 3, 1, 15)

Initial Balance: $ 500
Final Balance: $ 1875.5728510222339
Total Staked: $ 3851.5697215688306
ROI:  0.35714603407514905
Average wager: $ 41.86488827792207
Win Rate:  0.6739130434782609

In [127]:
test_strat(500, 3, 1, 20)

Initial Balance: $ 500
Final Balance: $ 2325.644753743046
Total Staked: $ 5104.759628758444
ROI:  0.35763579218461083
Average wager: $ 55.486517703896126
Win Rate:  0.6739130434782609

In [128]:
test_strat(500, 4, 1, 15)

Initial Balance: $ 500
Final Balance: $ 1536.6494857674425
Total Staked: $ 2688.017761401469
ROI:  0.3856557425524442
Average wager: $ 41.35411940617645
Win Rate:  0.676923076923077

In [129]:
test_strat(500, 3, 0, 15)

Initial Balance: $ 500
Final Balance: $ 1850.215708162434
Total Staked: $ 3759.5697215688306
ROI:  0.3591410209567819
Average wager: $ 40.86488827792207
Win Rate:  0.6739130434782609

In [130]:
test_strat(500, 3, 1, 15)

Initial Balance: $ 500
Final Balance: $ 1875.5728510222339
Total Staked: $ 3851.5697215688306
ROI:  0.35714603407514905
Average wager: $ 41.86488827792207
Win Rate:  0.6739130434782609

In [131]:
test_strat(500, 3, 0, 10)

Initial Balance: $ 500
Final Balance: $ 1400.143805441623
Total Staked: $ 2506.379814379222
ROI:  0.3591410209567818
Average wager: $ 27.243258851948063
Win Rate:  0.6739130434782609

In [133]:
test_strat(500, 10, 0, 10)

Initial Balance: $ 500
Final Balance: $ 580.5467076707465
Total Staked: $ 144.48431258552972
ROI:  0.5574771837120078
Average wager: $ 36.12107814638243
Win Rate:  0.75